# Generated by Django 6.0.5 on 2026-05-09 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation_type', '0001_initial'),
        ('doctor', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text="Client's name", max_length=200)),
                ('last_name', models.CharField(help_text="Client's last name", max_length=200)),
                ('date_of_birth', models.DateField(blank=True, help_text="Client's date of birth", null=True)),
                ('state', models.CharField(blank=True, help_text="Client's state of residence", max_length=100, null=True)),
                ('biological_sex', models.CharField(blank=True, help_text="Client's biological sex", max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text="Client's email address", max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text="Client's phone number", max_length=20, null=True)),
                ('reason_for_visit', models.TextField(blank=True, help_text='Reason for the visit', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications', null=True)),
                ('known_allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('medical_history_info', models.TextField(blank=True, help_text='Medical history', null=True)),
                ('appointment_time', models.DateTimeField(help_text='Scheduled appointment date and time')),
                ('is_paid', models.BooleanField(default=False, help_text='Payment status')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Appointment amount', max_digits=10)),
                ('payment_method', models.CharField(help_text='Payment method', max_length=155)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Appointment status', max_length=20)),
                ('agreed_to_telehealth', models.BooleanField(default=False)),
                ('agreed_to_privacy_policy', models.BooleanField(default=False)),
                ('agreed_to_hipaa', models.BooleanField(default=False)),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultation_type.consultationtype')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service.service')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=250)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointment.appointment')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['-appointment_time'], name='appointment_appoint_a7db97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_time')},
        ),
    ]
