# Generated by Django 6.0.5 on 2026-05-09 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('description', models.TextField(help_text='Service description')),
                ('lab_recommended', models.BooleanField(default=False, help_text='Lab recommended')),
                ('products', models.ManyToManyField(blank=True, help_text='Products associated with this service', related_name='services', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
